"""
Django settings for webproject project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x*2eiugnl&w3h8iew-t)ra7ca$8jsra4nkwzrr$z_ef-49zx5z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'procedure44EK.apps.Procedure44EkConfig',
    'procedure44EA.apps.Procedure44EaConfig',
    'protocol.apps.ProtocolConfig',

    'rest_framework',
    'corsheaders',
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True


ROOT_URLCONF = 'webproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'web-ui/build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'edo': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'edo',
        'USER': os.environ.get('etpuser'),
        'PASSWORD': os.environ.get('etpdbpass'),
        'HOST': os.environ.get('etp_database_ip'),
        'PORT': '4322',

    },
    'mydb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mydb',
        'USER': os.environ.get('mydbuser'),
        'PASSWORD': os.environ.get('mydbpass'),
        'HOST': os.environ.get('mydbip'),
        'PORT': '3306',

    },
    'sectionks': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sectionks',
        'USER': os.environ.get('etpuser'),
        'PASSWORD': os.environ.get('etpdbpass'),
        'HOST': os.environ.get('etp_database_ip'),
        'PORT': '4301',

    },
     '44ek': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '44ek',
        'USER': os.environ.get('etpuser'),
        'PASSWORD': os.environ.get('etpdbpass'),
        'HOST': os.environ.get('etp_database_ip'),
        'PORT': '43137',

    },
     'catalog_44': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'catalog_44',
        'USER': os.environ.get('etpuser'),
        'PASSWORD': os.environ.get('etpdbpass'),
        'HOST': os.environ.get('etp_database_ip'),
        'PORT': '43141',
    },


}

DATABASE_ROUTERS = ['procedure44EK.models.EDORouter']
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
STATICFILES_DIRS = (
 os.path.join(BASE_DIR,'web-ui/build/static'),
)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


GRAPH_MODELS = {
  'all_applications': True,
  'group_models': True,
}

PROTOCOL_PROCEDURES = [125,127,131,133,135,141,143,145,147,149,155,157,159,161,163,169,171,173,175,177,179,305,307,309,313,327,333]